# Generated by Django 6.0.3 on 2026-03-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='pickup_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='network.node'),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rides.carpoolrequest'),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_currently_at', to='network.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_ending', to='network.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_starting', to='network.node'),
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='confirmed_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_passengers', to='rides.trip'),
        ),
        migrations.AddField(
            model_name='carpooloffer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='rides.trip'),
        ),
        migrations.AddField(
            model_name='tripsequence',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.node'),
        ),
        migrations.AddField(
            model_name='tripsequence',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_sequence', to='rides.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='tripsequence',
            unique_together={('trip', 'node')},
        ),
    ]
